import pandas as pd

def load_data(file_path):
    """Load data from the CSV file."""
    return pd.read_csv(file_path)

def compute_monthly_revenue(df):
    """Compute the total revenue generated by the online store for each month."""
    df['order_date'] = pd.to_datetime(df['order_date'])
    df['month'] = df['order_date'].dt.to_period('M')
    monthly_revenue = df.groupby('month').apply(lambda x: (x['product_price'] * x['quantity']).sum())
    return monthly_revenue

def compute_product_revenue(df):
    """Compute the total revenue generated by each product."""
    product_revenue = df.groupby('product_name').apply(lambda x: (x['product_price'] * x['quantity']).sum())
    return product_revenue

def compute_customer_revenue(df):
    """Compute the total revenue generated by each customer."""
    customer_revenue = df.groupby('customer_id').apply(lambda x: (x['product_price'] * x['quantity']).sum())
    return customer_revenue

def top_customers_by_revenue(df, top_n=10):
    """Identify the top N customers by revenue generated."""
    customer_revenue = compute_customer_revenue(df)
    top_customers = customer_revenue.nlargest(top_n)
    return top_customers

if __name__ == "__main__":
    file_path = 'orders.csv'
    df = load_data(file_path)
    
    monthly_revenue = compute_monthly_revenue(df)
    print("Monthly Revenue:")
    print(monthly_revenue)
    
    product_revenue = compute_product_revenue(df)
    print("Product Revenue:")
    print(product_revenue)
    
    customer_revenue = compute_customer_revenue(df)
    print("Customer Revenue:")
    print(customer_revenue)
    
    top_customers = top_customers_by_revenue(df)
    print("Top 10 Customers by Revenue:")
    print(top_customers)
